### ISSUE TITLE
Removing a URL from cache

### ISSUE THREAD

**Issue by kushalbhabra** [koush/UrlImageViewHelper#61]
I try to access same URL for loading an image for a user.

I use UrlImageViewHelper.setDrawable(imageView,url) in my UserProfile activity

So when I update image at that URL, I call UrlImageViewHelper.remove(url,this)  in my activity which I believe should remove that URL from cache and get updated image on calling UrlImageViewHelper.setDrawable(imageView,url) but it doesn't work. It fetches image from cache.

Is the context "this"wrong? in UrlImageViewHelper.remove(url,this) 
What should I use instead?

**Comment by FrancescLlao** [comment]
A few days ago I published something like this.
If there is no internet, onLoaded method returns null bitmap, and cache is keeping a null bitmap.
The best thing would be to remove the url from cache but this method does not work.

**Comment by koush** [comment]
```
public static Bitmap remove(String url)
```

This method should work. I don't see a method that takes two arguments?

**Comment by wxf04125** [comment]
Hello, I still can't remove the cached url image.The remove(String url) method return the bitmap i have set before.But when i call UrlImageViewHelper.setDrawable(imageView,url), the removed bitmap show again.I hava downloaded the newest jar lib from the github page. I need your help.

**Comment by loop89** [comment]
Please update I'm having the same error .. with urlimagehelper in xamarin android..

**Comment by loop89** [comment]
Please update for removing an image from cache..
